project:
  type: website
  output-dir: docs

website:
  title: "Felix MIL"
  navbar:
    right:
      - blog.qmd
      - software.qmd
      - text: About
        href: about.qmd
      - icon: twitter
        href: https://twitter.com/felix_mil_
      - icon: mastodon
        href: https://fosstodon.org/@felix_mil
      - icon: linkedin
        href: https://www.linkedin.com/in/felix-mil/
      - icon: github
        href: https://github.com/Felixmil/felixmil.github.io
      - icon: envelope-fill
        href: mailto:felix.mil.dev@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css
    
    
execute:
  freeze: auto  # re-render only when source changes