project:
  type: website

website:
  title: "felixmil.com"
  navbar:
    right:
      - text: Now
        href: now.md
      - text: Blog
        href: blog.md

format:
  html:
    theme: litera
    css: styles.css



