project:
  type: website

website:
  repo-url: "https://github.com/Felixmil/felixmil.com"
  site-url: "https://felixmil.com"
  title: "Felix MIL"
  navbar:
    right:
      - text: Blog
        href: blog.md
      - text: Now
        href: now.md
      - text: About
        href: about.md

format:
  html:
    theme: [brand]
    css: styles.css
    
execute:
  freeze: auto



