project:
  type: website
  output-dir: docs

website:
  title: "Felix MIL"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Felixmil/felixmil.github.io
      - icon: twitter
        href: https://twitter.com/felix_mil_
format:
  html:
    theme: cosmo
    css: styles.css



