---
title: "Software"
---


# [`{esqlabsR}`](https://github.com/esqLABS/esqlabsR)
Designed to facilitate and standardize modeling and simulation (M&S) of PBPK and QSP models implemented in Open Systems Pharmacology Software (OSPS) and executed from R. The package provides functions to read and run scenarios, workflows, and simulations. Furthermore, it creates visualizations based on non-code input from Excel files. The package is based on R functions in the ospsuite R package.

# [`{ospsuite}`](https://github.com/Open-Systems-Pharmacology/OSPSuite-R)
Provides the functionality of loading, manipulating, and simulating the simulations created in the Open Systems Pharmacology Software tools PK-Sim and MoBi.

# [`{TLF}`](https://github.com/Open-Systems-Pharmacology/TLF-Library)
Provides an object-oriented framework to create tables and figures, which are used by R packages in the Open Systems Pharmacology ecosystem

# [`{RollR`}](https://github.com/Felixmil/rollR)
Provides a simple way to make all sorts of dice rolls using syntax inspired from tabletop roleplaying games like Dungeons & Dragons.