---
title: "Advent of Code - Day 9: Rope Bridge"
subtitle: "9h day of the advent of code using R"
date: 2022-12-09
categories: "advent of code"
format: 
   html:
     df-print: paged
editor: 
  markdown: 
    wrap: 80
editor_options: 
  chunk_output_type: console
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '',
  message = F,
  warning = F
)
```


# Part 1


## Input


```{r}
sample <-   readLines("sample.txt")
```


```{r}
input <- readLines("input.txt")

 head(input, 10)
```

# Part 1


## Code


```{r}
move_knot <- function(head_coord, knot_coord) {
  
  x_diff = abs(head_coord$x - knot_coord$x)
  y_diff = abs(head_coord$y - knot_coord$y)
  
  diff_sum <- abs(x_diff) + abs(y_diff)
  
  if (x_diff > 1 | y_diff > 1) {
    available_coord <- list(
      list(x = knot_coord$x + 1, y = knot_coord$y),
      list(x = knot_coord$x + 1, y = knot_coord$y + 1),
      list(x = knot_coord$x + 1, y = knot_coord$y - 1),
      list(x = knot_coord$x - 1, y = knot_coord$y),
      list(x = knot_coord$x - 1, y = knot_coord$y + 1),
      list(x = knot_coord$x - 1, y = knot_coord$y - 1),
      list(x = knot_coord$x, y = knot_coord$y + 1),
      list(x = knot_coord$x, y = knot_coord$y - 1),
      list(x = knot_coord$x, y = knot_coord$y)
    )
    
    coord_diff <-
      purrr::map(available_coord,
                 ~ abs(.x$x - head_coord$x) + abs(.x$y - head_coord$y))
    
    knot_coord <- available_coord[[which(diff == min(diff))]]
    
    return(knot_coord)
    
  }
}

```


```{r}
moves <- input

head_coord <- list(x=0,y=0)
tail_coord <- list(x=0,y=0)

visited_coord <- c()

for (move in moves) {
  
  move_vec <- unlist(strsplit(move, " "))
  
  direction <- move_vec[1]
  distance <- move_vec[2]
  
  for (d in 1:distance) {
    # message(d)
    if (direction == "R") {
      head_coord$x <- head_coord$x + 1
    } else if (direction == "L"){
      head_coord$x = head_coord$x - 1
    } else if (direction == "U") {
      head_coord$y = head_coord$y + 1
    } else if (direction == "D") {
      head_coord$y = head_coord$y - 1
    }
    
    tail_coord <- move_knot(head_coord, tail_coord)
    
    visited_coord <- c(visited_coord, paste(tail_coord$x, tail_coord$y, sep =  ";"))
  }
}


```

# Part 2

```{r}
sample2 <- readLines("sample2.txt")
```


```{r}

knots <- list()

knots <- vector("list", 10)

for (i in 1:10) {
  knots[[i]] <- list(x=0, y=0)
}

moves <- input
visited_coord <- c()

for (move in moves) {

  move_vec <- unlist(strsplit(move, " "))
  
  direction <- move_vec[1]
  distance <- move_vec[2]
  
  for (d in 1:distance) {
    if (direction == "R") {
      knots[[1]]$x <- knots[[1]]$x + 1
    } else if (direction == "L"){
      knots[[1]]$x = knots[[1]]$x - 1
    } else if (direction == "U") {
      knots[[1]]$y = knots[[1]]$y + 1
    } else if (direction == "D") {
      knots[[1]]$y = knots[[1]]$y - 1
    }
    for (i in 2:10) {
      new_coord <- move_knot(direction, knots[[i-1]], knots[[i]])
      if (new_coord$x != knots[[i]]$x | new_coord$y != knots[[i]]$y) {
        knots[[i]] <- new_coord
      } else{
        break
      }
      
    }
    visited_coord <- c(visited_coord, paste(knots[[10]]$x, knots[[10]]$y,sep = ";"))
  }
  
}

length(unique(visited_coord))
```
