---
title: "Advent of Code - Day 3: Rucksack Reorganization"
subtitle: "Third day of the advent of code using R"
date: 2022-12-03
categories: "advent of code"
format: 
   html:
     df-print: paged
editor: 
  markdown: 
    wrap: 80
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '',
  message = F, 
  warning = F
)
```

# Part 1

## Input

```{r}
input <- readLines("input.txt")

head(input, 10)
```

## Libraries

```{r}
```

## Code

```{r}
find_common <- function(rucksack){
  len <- nchar(rucksack)
  chars <- unlist(strsplit(rucksack, ""))
  first_part <- chars[1:(len/2)]
  second_part <- chars[(len/2)+1:len]
  return(intersect(first_part, second_part))
}

get_priority <- function(item){
  if(item %in% LETTERS){
    priority <- 26 + match(item, LETTERS)
  } else {
    priority <- match(item, letters)
  }
  return(priority)
}
```


```{r}
sum_priority <- 0

for (i in input) {
  common_item <- find_common(i)
  priority <- get_priority(common_item)
  sum_priority <- sum_priority + priority
}
```


## Result

Total sum of all priorities is **`r format(sum_priority, scientific=F)`**.

# Part 2

```{r}
find_identifier <- function(rucksacks) {
  
  rucksacks_content <- list(unlist(strsplit(rucksacks[[1]], "")),
                            unlist(strsplit(rucksacks[[2]], "")),
                            unlist(strsplit(rucksacks[[3]], "")))
  identifier <- purrr::reduce(rucksacks_content, intersect)
  
  
  
  return(identifier)
  
}

total_priority <- 0

for (i in seq(1,length(input), by = 3)) {
  rucksacks <- list(input[i],
                    input[i+1],
                    input[i+2])
  
  identifier <- find_identifier(rucksacks)
  priority <- get_priority(identifier)
  total_priority <- total_priority + priority
}

total_priority
```

## Result

Total sum of all priorities is **`r format(total_priority, scientific=F)`**.

