---
title: "Advent of Code - Day 4: Camp Cleanup"
subtitle: "Fourth day of the advent of code using R"
date: 2022-12-04
categories: "advent of code"
format: 
   html:
     df-print: paged
editor: 
  markdown: 
    wrap: 80
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '',
  message = F, 
  warning = F
)
```


# Part 1
## Input

```{r}
input <- readLines("input.txt")

head(input, 10)
```


## Code

```{r}
# Function to count the number of overlapping pairs
count_overlapping_pairs <- function(pairs) {
  # Initialize a counter variable
  count <- 0

  # Loop through each pair
  for (pair in pairs) {
    # Split the pair into its start and end parts
    parts <- unlist(strsplit(pair, ","))
    
    first_elf <- as.numeric(unlist(strsplit(parts[1], "-")))
    second_elf <-  as.numeric(unlist(strsplit(parts[2], "-")))
    
    first_set <- c(first_elf[1]:first_elf[2])
    second_set <- c(second_elf[1]:second_elf[2])
    
    
    if (identical(first_set[first_set %in% second_set],first_set) || identical(second_set[second_set %in% first_set],second_set)) {
      count <- count + 1
    }
  }

  # Return the count
  return(count)
}
```

```{r}
result <- count_overlapping_pairs(input)
```


## Result

There are a total of **`r format(result, scientific=F)`** fully overlapping pairs.


# Part 2

```{r}
# Function to count the number of overlapping pairs
count_overlapping_pairs <- function(pairs) {
  # Initialize a counter variable
  count <- 0

  # Loop through each pair
  for (pair in pairs) {
    # Split the pair into its start and end parts
    parts <- unlist(strsplit(pair, ","))
    
    first_elf <- as.numeric(unlist(strsplit(parts[1], "-")))
    second_elf <-  as.numeric(unlist(strsplit(parts[2], "-")))
    
    first_set <- c(first_elf[1]:first_elf[2])
    second_set <- c(second_elf[1]:second_elf[2])
    
    
    if (length(intersect(first_set, second_set) > 0)) {
      count <- count + 1
    }
  }

  # Return the count
  return(count)
}

result <- count_overlapping_pairs(input)
```


There are a total of **`r format(result, scientific=F)`** partialy overlapping pairs.

